#!/usr/bin/env python
# coding: utf-8

# # Processing UV-Vis spectra obtained from the Cary 50 spectrophotometer
# 
# 0. Imports

# In[116]:


import os
import csv
import numpy
from collections import defaultdict
from .util import isFloat


# 1. Each file from the Cary 50 can have more than one spectrum.

# In[121]:


def readSpectraFromFile(path_to_file):
    '''Extracts the absorption spectrum from the text file generated by a Beckman Coulter DU-640 spectrophotometer

    Parameters
    ----------
    path_to_file : string
        Path used to locate the spectrum text file.

    Returns
    -------
    array of tuples
       absorption spectrum
       The first element of each tuple is the wavelength in nanometers. 
       The second element is the absorbance measurement in absorbance units.
    '''
    with open(path_to_file) as f:
        reader = csv.reader(f)
        data = []
        for row in reader:
            data.append(row)
        labels = list(filter(lambda x: x, data[0]))
        data = numpy.array([numpy.array(row) for row in data[2:]],dtype=object).T
        wavelengths = list(data[0].astype(numpy.float))
        merged_spectra = defaultdict(list)
        i = 1
        for label in labels:
            merged_spectra[label] = list(data[i].astype(numpy.float))
            i = i+2
    return (wavelengths, merged_spectra)

